### ISSUE TITLE
Unit uFlxPanel is missing in Source

### ISSUE THREAD

**Issue by CommanderTom66** [holgerflick/flixaccounting#23]
The Unit UFrmReportHost uses uFlxPanel, which is not included in the Source. There are two Panels (panTop and panHost), which references to TFlxPanel. Without the File uFlxPanel, compiling is not possible.

**Comment by holgerflick** [comment]
Hi Thomas,

 

Thank you for the report.

 

Originally, I wanted to also show an intro to component development, but decided against it in the end. I did remove those references. Will check again.

 

Regards,

Holger Flick

 

--

Dr. Holger Flick

Chief Executive Officer, FlixEngineering LLC

P: 239.315.1042


Estero, FL  33928 |  United States of America

 

From: Thomas Speck ***@***.***> 
Sent: Saturday, December 30, 2023 10:23 AM
To: holgerflick/flixaccounting ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [holgerflick/flixaccounting] Unit uFlxPanel ist missing in Source (Issue #23)

 

The Unit UFrmReportHost uses uFlxPanel, which is not included in the Source. There are two Panels (panTop and panHost), which references to TFlxPanel. Without the File uFlxPanel, compiling is not possible.

**Comment by holgerflick** [comment]
Can you please make sure that you are using the `main` branch? I works fine here. I removed uFlxPanel.pas/dcu from my system and the project builds fine.

**Comment by holgerflick** [comment]
![image](https://github.com/holgerflick/flixaccounting/assets/1275944/ac99715d-fa65-4e45-b585-a91a74e31d03)

![image](https://github.com/holgerflick/flixaccounting/assets/1275944/421fa244-e4aa-4771-8dac-b9985a14de64)

![image](https://github.com/holgerflick/flixaccounting/assets/1275944/e6847b49-e778-476e-9fc9-439ad6a64026)

**Comment by CommanderTom66** [comment]
I load the Files again from Source Code.zip in your Repositiry from August 2023, but the Error persists. Are these Files not Up-To-Date?

**Comment by holgerflick** [comment]
The files should be from today as reader Thorsten suggested some adjustments for Delphi 12. I see my mistake now. THANK YOU @CommanderTom66 ! I will fix it. Give me 5 minutes.

**Comment by holgerflick** [comment]
I added a new release. However, you can always download the most recent version here:

![image](https://github.com/holgerflick/flixaccounting/assets/1275944/87302ae5-ce81-47b7-ac37-14b36d11d2b3)

**Comment by CommanderTom66** [comment]
Thank you, all is working now fine.

**Comment by holgerflick** [comment]
Thank you for using this board to resolve the issue quickly. And as always, Thomas, **thank you** for your support of my book and other projects!

**Comment by CommanderTom66** [comment]
I appreciate your way of coding and explaining things in Youtube and in your Books. I've bought all of them and they have a place of honor in my bookshelf and I'm thrilled whats cooking in the Labs ;-)
